// src/pages/ClassroomDetailsPage.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import attendanceService from "@/api/services/attendanceService";
import type {
  Attendance,
  AttendanceStatus,
} from "@/types/attendance";
import { Card, CardContent } from "@/components/ui/card";
import { Spinner } from "@/components/ui/spinner";
import { toast } from "sonner";
import { Container } from "@/components/common/container";
import { useClassroom } from "@/context/classroom/useClassroom";
import { StudentsTable } from "../components/student/students-table";
import { toBackendStatus } from "@/util/attendance";
import { ClassroomHeader } from "@/components/classroom/classroom-header";

/**
 * @description This is the main page component for displaying the details of a classroom.
 * It has been refactored to use a custom hook (useClassroom) and several sub-components
 * (ClassroomHeader, AttendanceTable, AddStudentDialog) to improve modularity and readability.
 * The core logic is now separated into smaller, more manageable pieces.
 */
export const ClassroomDetailsPage: React.FC = () => {
  const {
    classroom,
    loading,
    attendances,
    setAttendances,
    fetchClassroomData,
  } = useClassroom();
  const navigate = useNavigate();

  const [isAttendanceMode, setIsAttendanceMode] = useState(false);

  const handleStartAttendance = () => {
    if (classroom) {
      if (classroom.chamada_feita) {
        // If attendance is already done, just enter attendance mode
        // The existing attendances are already loaded by the hook
      } else {
        // If not, start everyone as 'Presente'
        const newAttendances: Attendance[] = classroom.estudantes.map(
          (student) => ({
            id: "", // ID will be generated by the backend
            estudante: student,
            data_presenca: null,
            status: "Presente",
          })
        );
        setAttendances(newAttendances);
      }
      setIsAttendanceMode(true);
    }
  };

  const handleAttendanceChange = (
    studentId: string,
    status: AttendanceStatus
  ) => {
    setAttendances((prev) => {
      const existingAttendance = prev.find(
        (att) => att.estudante.id === studentId
      );

      if (existingAttendance) {
        return prev.map((att) =>
          att.estudante.id === studentId ? { ...att, status } : att
        );
      }

      const student = classroom?.estudantes.find((s) => s.id === studentId);
      if (student) {
        const newAttendance: Attendance = {
          id: "",
          estudante: student,
          data_presenca: new Date(),
          status,
        };
        return [...prev, newAttendance];
      }

      return prev;
    });
  };

  const handleSaveAttendance = async () => {
    if (!classroom || !attendances) return;

    const attendanceList = attendances.map(({ id, estudante, status }) => ({
      id,
      estudante,
      status: toBackendStatus(status as AttendanceStatus),
    } as Attendance));

    try {
      if (classroom.chamada_feita) {
        await attendanceService.updateAttendanceByClassroomAndDate(
          classroom.id,
          null,
          attendanceList
        );
        toast.success("Presença atualizada com sucesso!");
      } else {
        await attendanceService.insertAttendanceByClassroomAndDate(
          classroom.id,
          null,
          attendanceList
        );
        toast.success("Presença registrada com sucesso!");
      }
      setIsAttendanceMode(false);
      fetchClassroomData(); // Re-fetch classroom data
    } catch (error) {
      console.error("Erro ao salvar presença:", error);
      toast.error("Erro ao salvar presença.");
    }
  };

  const handleRowClick = (studentId: string) => {
    if (!isAttendanceMode) {
      navigate(`/estudantes/${studentId}`);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <Spinner />
      </div>
    );
  }

  if (!classroom) {
    return (
      <div className="text-center p-4">
        <h1 className="text-xl">Turma não encontrada.</h1>
      </div>
    );
  }

  return (
    <Container>
      <Card className="w-full h-full flex flex-col">
        <ClassroomHeader
          isAttendanceMode={isAttendanceMode}
          onStartAttendance={handleStartAttendance}
          onCancelAttendance={() => setIsAttendanceMode(false)}
          onSaveAttendance={handleSaveAttendance}
        />
        <CardContent className="flex-1 overflow-auto">
          <StudentsTable
            isAttendanceMode={isAttendanceMode}
            onAttendanceChange={handleAttendanceChange}
            onRowClick={handleRowClick}
          />
        </CardContent>
      </Card>
    </Container>
  );
};
